POST http://127.0.0.1:5000/timeArray
Content-Type: application/json

{}

###
GET http://127.0.0.1:5000/timeArray
Accept: application/json

###
GET http://127.0.0.1:5000/currentTime
Accept: application/json

###
